# Generated by Django 4.0.6 on 2022-12-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0002_hmiseries_name_hmimodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hmimodel',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='hmiseries',
            options={'ordering': ('brand', 'name'), 'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.AlterField(
            model_name='hmimodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Название'),
        ),
    ]
