# Generated by Django 4.0.6 on 2022-12-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0004_alter_hmimodel_options_hmimodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmimodel',
            name='image',
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка1'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка2'),
        ),
    ]
