# Generated by Django 4.0.6 on 2022-12-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0005_remove_hmimodel_image_hmimodel_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='power_range',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(43, '4.3"'), (70, '7"'), (100, '10"'), (120, '12"'), (150, '15"')], null=True, verbose_name='Диагональ'),
        ),
    ]
