# Generated by Django 4.0.6 on 2022-12-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0006_hmimodel_power_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hmimodel',
            old_name='power_range',
            new_name='diagonal',
        ),
    ]
