# Generated by Django 4.0.6 on 2022-12-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0007_rename_power_range_hmimodel_diagonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='resolution',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, '480x272')], null=True, verbose_name='Разрешение'),
        ),
    ]
