# Generated by Django 4.0.6 on 2022-12-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0008_hmimodel_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='display_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, 'TFT (65536 цветов)')], null=True, verbose_name='Тип дисплея'),
        ),
    ]
