# Generated by Django 4.0.6 on 2022-12-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0009_hmimodel_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='supply_voltage',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, '24VDC')], null=True, verbose_name='Питание'),
        ),
    ]
