# Generated by Django 4.0.6 on 2022-12-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0010_hmimodel_supply_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='cpu',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, 'Cortex-A8 (800 МГц)')], null=True, verbose_name='Процессор'),
        ),
    ]
