# Generated by Django 4.0.6 on 2022-12-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0011_hmimodel_cpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='protection_degree',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, 'IP65')], null=True, verbose_name='Степень защиты лицевой панели'),
        ),
    ]
