# Generated by Django 4.0.6 on 2022-12-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0012_hmimodel_protection_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='flash_rom',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, 'IP65')], null=True, verbose_name='ПЗУ (Flash-ROM)'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='ram',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, '256MB')], null=True, verbose_name='ОЗУ (RAM)'),
        ),
    ]
