# Generated by Django 4.0.6 on 2022-12-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0013_hmimodel_flash_rom_hmimodel_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='sd_card',
            field=models.BooleanField(blank=True, null=True, verbose_name='Слот для SD карты'),
        ),
        migrations.AlterField(
            model_name='hmimodel',
            name='flash_rom',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, '256MB')], null=True, verbose_name='ПЗУ (Flash-ROM)'),
        ),
    ]
