# Generated by Django 4.0.6 on 2022-12-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0016_hmimodel_audio_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='video_playback_from_media',
            field=models.BooleanField(blank=True, null=True, verbose_name='Воспроизведение видео с носителей'),
        ),
    ]
