# Generated by Django 4.0.6 on 2022-12-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0018_hmimodel_vga_playback'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='ip_cameras_support',
            field=models.BooleanField(blank=True, null=True, verbose_name='Поддержка IP-камер'),
        ),
    ]
