# Generated by Django 4.0.6 on 2022-12-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0019_hmimodel_ip_cameras_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='analog_cameras_support',
            field=models.BooleanField(blank=True, null=True, verbose_name='Поддержка аналоговых камер'),
        ),
    ]
