# Generated by Django 4.0.6 on 2022-12-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0020_hmimodel_analog_cameras_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='communication_interfaces',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, 'USB Type-A (Host); USB Type-B (Slave - порт загрузки); COM1 RS232; COM2 RS422/485')], null=True, verbose_name='Интерфейсы связи'),
        ),
    ]
