# Generated by Django 4.0.6 on 2022-12-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0021_hmimodel_communication_interfaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='com_port',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, '1 порт'), (20, '2 порта'), (30, '3 порта'), (40, '4 порта')], null=True, verbose_name='COM-порт'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='ethernet_port',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, '1 порт'), (20, '2 порта'), (30, '3 порта'), (40, '4 порта')], null=True, verbose_name='Ethernet-порт'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='real_time_clock',
            field=models.BooleanField(blank=True, null=True, verbose_name='Часы реального времени'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='usb_port',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, '1 порт'), (20, '2 порта'), (30, '3 порта'), (40, '4 порта')], null=True, verbose_name='USB-порт'),
        ),
    ]
