# Generated by Django 4.0.6 on 2022-12-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0022_hmimodel_com_port_hmimodel_ethernet_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='cloud_technology',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Нет на территории РБ (только в некоторых странах Азии)'), (30, 'Да')], null=True, verbose_name='Поддержка облачных технологий'),
        ),
    ]
