# Generated by Django 4.0.6 on 2022-12-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0023_hmimodel_cloud_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='input_in_russian',
            field=models.BooleanField(blank=True, null=True, verbose_name='Поддержка ввода на русском языке'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='network_technologies',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, 'Сервер VNC (удаленный мониторинг), Сервер FTP')], null=True, verbose_name='Поддерживаемые сетевые технологии'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='opc_ua_support',
            field=models.BooleanField(blank=True, null=True, verbose_name='Поддержка OPC UA'),
        ),
    ]
