# Generated by Django 4.0.6 on 2022-12-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0024_hmimodel_input_in_russian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='communication_drivers',
            field=models.BooleanField(blank=True, null=True, verbose_name='Библиотека драйверов связи с другими производителями'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='data_archiving',
            field=models.BooleanField(blank=True, null=True, verbose_name='Функции архивации данных (по таймеру, событию) аварий, действий оператора и выгрузка на внешний носитель'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='gif_animation',
            field=models.BooleanField(blank=True, null=True, verbose_name='Поддержка GIF анимации'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='library_visualization_elements',
            field=models.BooleanField(blank=True, null=True, verbose_name='Библиотека стандартных элементов визуализации'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='macro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Поддержка макросов'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='printer_communication',
            field=models.BooleanField(blank=True, null=True, verbose_name='Поддержка связи с принтером'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='recipe',
            field=models.BooleanField(blank=True, null=True, verbose_name='Поддержка рецептов (сменные наборы технологических параметров)'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='script',
            field=models.BooleanField(blank=True, null=True, verbose_name='Поддержка скриптов'),
        ),
    ]
