# Generated by Django 4.0.6 on 2022-12-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0026_hmimodel_user_rights_separation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='pdf_support',
            field=models.BooleanField(blank=True, null=True, verbose_name='Поддержка чтения PDF'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='trends',
            field=models.BooleanField(blank=True, null=True, verbose_name='Формирование трендов'),
        ),
    ]
