# Generated by Django 4.0.6 on 2022-12-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0027_hmimodel_pdf_support_hmimodel_trends'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='pc_software',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, 'Да (бесплатный)')], null=True, verbose_name='Софт для отладки на ПК'),
        ),
    ]
