# Generated by Django 4.0.6 on 2022-12-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0028_hmimodel_pc_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmimodel',
            name='russian_software',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, 'Частично')], null=True, verbose_name='Софт на русском'),
        ),
        migrations.AddField(
            model_name='hmimodel',
            name='simulation',
            field=models.BooleanField(blank=True, null=True, verbose_name='Поддержка симуляции софтом'),
        ),
    ]
