# Generated by Django 4.0.6 on 2022-09-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='emc_filter',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Нет'), (1, 'C3'), (2, 'C2')], default=0, verbose_name='Встроенный EMC фильтр'),
            preserve_default=False,
        ),
    ]
