# Generated by Django 4.0.6 on 2022-07-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0002_country_brand_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='site',
            field=models.SlugField(default=1, max_length=150, verbose_name='Сайт'),
            preserve_default=False,
        ),
    ]
