# Generated by Django 4.0.6 on 2022-07-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0003_brand_description_brand_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Линейка оборудования',
                'verbose_name_plural': 'Линейки оборудования',
            },
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='brand',
            name='equipment_lines',
            field=models.ManyToManyField(to='vfd.equipmentline'),
        ),
    ]
