# Generated by Django 4.0.6 on 2022-07-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0004_equipmentline_alter_brand_name_brand_equipment_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='equipment_lines',
            field=models.ManyToManyField(to='vfd.equipmentline', verbose_name='Линейки оборудования'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='site',
            field=models.CharField(max_length=150, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='series',
            name='applications',
            field=models.ManyToManyField(to='vfd.application', verbose_name='Применения'),
        ),
    ]
