# Generated by Django 4.0.6 on 2022-09-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0004_alter_series_pulse_frequency_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='pulse_frequency_setting',
        ),
    ]
