# Generated by Django 4.0.6 on 2022-09-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0005_remove_series_pulse_frequency_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='pulse_frequency_setting',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Нет'), (1, 'Да')], default=0, verbose_name='Импульсное задание частоты'),
            preserve_default=False,
        ),
    ]
