# Generated by Django 4.0.6 on 2022-07-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0005_alter_brand_equipment_lines_alter_brand_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='additional_communications',
            field=models.CharField(default=1, max_length=200, verbose_name='Дополнительные протоколы связи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='analog_inputs',
            field=models.IntegerField(default=1, verbose_name='Аналоговые входы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='analog_outputs',
            field=models.IntegerField(default=1, verbose_name='Аналоговые выходы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='brake_interrupter',
            field=models.CharField(default=1, max_length=200, verbose_name='Тормозной прерыватель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='built_in_communication',
            field=models.CharField(choices=[('No', 'Нет'), ('ModBusRTU', 'RS-485 Modbus RTU')], default=1, max_length=200, verbose_name='Встроенный протокол связи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='built_in_plc',
            field=models.CharField(default=1, max_length=200, verbose_name='Встроенный ПЛК'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='choke_dc_link',
            field=models.CharField(default=1, max_length=10, verbose_name='Дроссель в звене постоянного тока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='control_panel',
            field=models.CharField(default=1, max_length=200, verbose_name='Панель управления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='digital_inputs',
            field=models.IntegerField(default=1, verbose_name='Дискретные входы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='emc_filter',
            field=models.CharField(choices=[('No', 'Нет'), ('C3', 'C3'), ('C2', 'C2'), ('No_C2', 'Нет/C2')], default=1, max_length=10, verbose_name='Встроенный EMC фильтр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='operating_temp',
            field=models.CharField(default=1, max_length=200, verbose_name='Рабочая температура'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='overload_capacity',
            field=models.CharField(default=1, max_length=200, verbose_name='Перегрузочная способность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='power_max',
            field=models.FloatField(default=1, verbose_name='Мощность, до'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='power_min',
            field=models.FloatField(default=1, verbose_name='Мощность, от'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='protection_degree',
            field=models.CharField(default=1, max_length=200, verbose_name='Степень защиты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='relay_outputs',
            field=models.IntegerField(default=1, verbose_name='Релейные выходы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='transistor_outputs',
            field=models.IntegerField(default=1, verbose_name='Транзисторные выходы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
