# Generated by Django 4.0.6 on 2022-09-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0006_series_pulse_frequency_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='analog_inputs',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Аналоговые входы'),
        ),
        migrations.AlterField(
            model_name='series',
            name='analog_outputs',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Аналоговые выходы'),
        ),
        migrations.AlterField(
            model_name='series',
            name='digital_inputs',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Дискретные входы'),
        ),
        migrations.AlterField(
            model_name='series',
            name='pulse_frequency_setting',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='Импульсное задание частоты'),
        ),
        migrations.AlterField(
            model_name='series',
            name='relay_outputs',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Релейные выходы'),
        ),
        migrations.AlterField(
            model_name='series',
            name='transistor_outputs',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Транзисторные выходы'),
        ),
    ]
