# Generated by Django 4.0.6 on 2022-07-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0007_category_remove_series_title_series_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='additional_communications',
            field=models.CharField(choices=[('No', 'Нет'), ('Expansion cards', 'Да, платы расширения')], max_length=200, verbose_name='Дополнительные протоколы связи'),
        ),
        migrations.AlterField(
            model_name='series',
            name='choke_dc_link',
            field=models.CharField(max_length=200, verbose_name='Дроссель в звене постоянного тока'),
        ),
    ]
