# Generated by Django 4.0.6 on 2022-09-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0010_alter_series_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='sto_function',
            field=models.BooleanField(blank=True, null=True, verbose_name='Стандарт безопасности STO'),
        ),
    ]
