# Generated by Django 4.0.6 on 2022-07-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0010_alter_frequencydrive_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencydrive',
            name='current',
            field=models.FloatField(default=1, verbose_name='Ток'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequencydrive',
            name='power',
            field=models.FloatField(choices=[(2.2, '2.2'), (7.5, '7.5'), (22, 22), (45, 45), (110, 110), (250, 250)], default=1, verbose_name='Мощность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequencydrive',
            name='voltage',
            field=models.FloatField(choices=[(380, 380), (220, 220)], default=380, verbose_name='Напряжение'),
        ),
    ]
