# Generated by Django 4.0.6 on 2022-07-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0011_frequencydrive_current_frequencydrive_power_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('site', models.CharField(max_length=150, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='suppliers',
            field=models.ManyToManyField(to='vfd.supplier', verbose_name='Поставщики'),
        ),
    ]
