# Generated by Django 4.0.6 on 2022-09-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0011_alter_series_sto_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='control_panel_at_distance',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Выносной пульт'),
        ),
    ]
