# Generated by Django 4.0.6 on 2022-07-11 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0012_supplier_brand_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vfd.country', verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
