# Generated by Django 4.0.6 on 2022-07-11 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0013_supplier_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BYN', 'BYN'), ('RUB', 'RUB'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=200, verbose_name='Наименование')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('frequency_drive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vfd.frequencydrive', verbose_name='Частотник')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vfd.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
