# Generated by Django 4.0.6 on 2022-07-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0014_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('RUB', 'RUB'), ('EUR', 'EUR'), ('USD', 'USD')], default=1, max_length=200, verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
