# Generated by Django 4.0.6 on 2022-07-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0015_supplier_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='currency',
        ),
    ]
