# Generated by Django 4.0.6 on 2022-07-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0016_remove_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencydrive',
            name='article',
            field=models.CharField(max_length=30, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='series',
            name='brake_interrupter',
            field=models.CharField(max_length=300, verbose_name='Тормозной прерыватель'),
        ),
        migrations.AlterField(
            model_name='series',
            name='choke_dc_link',
            field=models.CharField(max_length=300, verbose_name='Дроссель в звене постоянного тока'),
        ),
    ]
