# Generated by Django 4.0.6 on 2022-09-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0017_alter_series_starting_torque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='torque_accuracy',
        ),
        migrations.RemoveField(
            model_name='series',
            name='torque_limitation',
        ),
    ]
