# Generated by Django 4.0.6 on 2022-07-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0018_brand_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ('brand', 'name'), 'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='additional_communications',
            field=models.CharField(choices=[('No', 'Нет'), ('Expansion cards', 'Да, платы расширения'), ('ModBusRTU', 'RS-485 Modbus RTU'), ('CANopen', 'CANopen')], max_length=200, verbose_name='Дополнительные протоколы связи'),
        ),
        migrations.AlterField(
            model_name='series',
            name='built_in_plc',
            field=models.CharField(choices=[('No', 'Нет'), ('Yes', 'Да'), ('mini-PLC', 'mini-PLC'), ('SequenceProgramming', 'Программирование последовательности')], max_length=200, verbose_name='Встроенный ПЛК'),
        ),
        migrations.AlterField(
            model_name='series',
            name='operating_temp',
            field=models.CharField(choices=[('-10...+40', '-10...+40'), ('-10...+50', '-10...+50'), ('-15...+50', '-15...+50'), ('-20...+50', '-20...+50')], max_length=200, verbose_name='Рабочая температура'),
        ),
        migrations.AlterField(
            model_name='series',
            name='protection_degree',
            field=models.CharField(choices=[('IP20', 'IP20'), ('IP21', 'IP21'), ('IP55', 'IP55')], max_length=200, verbose_name='Степень защиты'),
        ),
    ]
