# Generated by Django 4.0.6 on 2022-09-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0018_remove_series_torque_accuracy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='output_frequency_accuracy',
        ),
    ]
