# Generated by Django 4.0.6 on 2022-07-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0019_alter_series_options_series_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequencydrive',
            options={'ordering': ('series__brand', 'article'), 'verbose_name': 'Частотник', 'verbose_name_plural': 'Частотники'},
        ),
        migrations.AddField(
            model_name='series',
            name='control_panel_included',
            field=models.BooleanField(default=1, verbose_name='Панель управления в комплекте'),
            preserve_default=False,
        ),
    ]
