# Generated by Django 4.0.6 on 2022-09-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0019_remove_series_output_frequency_accuracy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='acceleration_deceleration_time',
        ),
    ]
