# Generated by Django 4.0.6 on 2022-09-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0020_remove_series_acceleration_deceleration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='maximum_output_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '150% / 3 Гц'), (2, '160% / 0.5 Гц')], null=True, verbose_name='Максимальная выходная частот, Гц'),
        ),
    ]
