# Generated by Django 4.0.6 on 2022-07-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0020_alter_frequencydrive_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=30, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование')),
                ('series', models.ManyToManyField(to='vfd.series', verbose_name='Серии')),
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
                'ordering': ('series__brand', 'article'),
            },
        ),
    ]
