# Generated by Django 4.0.6 on 2022-09-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0021_alter_series_maximum_output_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='maximum_output_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '599 Гц; 90 кВт и выше: 400 Гц'), (2, '599')], null=True, verbose_name='Максимальная выходная частот, Гц'),
        ),
    ]
