# Generated by Django 4.0.6 on 2022-07-16 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0021_accessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип аксессуара',
                'verbose_name_plural': 'Тип аксессуаров',
            },
        ),
        migrations.AddField(
            model_name='accessory',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vfd.accessorytype', verbose_name='Тип аксессуара'),
            preserve_default=False,
        ),
    ]
