# Generated by Django 4.0.6 on 2022-07-17 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0022_accessorytype_accessory_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequencydrive',
            options={'ordering': ('series__brand', 'series__name', 'voltage', 'power'), 'verbose_name': 'Частотник', 'verbose_name_plural': 'Частотники'},
        ),
        migrations.AddField(
            model_name='price',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vfd.accessory', verbose_name='Аксессуар'),
        ),
        migrations.AlterField(
            model_name='frequencydrive',
            name='voltage',
            field=models.FloatField(choices=[(400, 400), (230, 230)], default=380, verbose_name='Напряжение'),
        ),
        migrations.AlterField(
            model_name='price',
            name='frequency_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vfd.frequencydrive', verbose_name='Частотник'),
        ),
    ]
