# Generated by Django 4.0.6 on 2022-08-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0023_alter_frequencydrive_options_price_accessory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('name',), 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='series',
            name='additional_communications',
            field=models.CharField(blank=True, choices=[('No', 'Нет'), ('Expansion cards', 'Да, платы расширения'), ('ModBusRTU', 'RS-485 Modbus RTU'), ('CANopen', 'CANopen')], max_length=200, null=True, verbose_name='Дополнительные протоколы связи'),
        ),
        migrations.AlterField(
            model_name='series',
            name='analog_inputs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Аналоговые входы'),
        ),
        migrations.AlterField(
            model_name='series',
            name='analog_outputs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Аналоговые выходы'),
        ),
        migrations.AlterField(
            model_name='series',
            name='brake_interrupter',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Тормозной прерыватель'),
        ),
        migrations.AlterField(
            model_name='series',
            name='built_in_communication',
            field=models.CharField(blank=True, choices=[('No', 'Нет'), ('ModBusRTU', 'RS-485 Modbus RTU')], max_length=200, null=True, verbose_name='Встроенный протокол связи'),
        ),
        migrations.AlterField(
            model_name='series',
            name='built_in_plc',
            field=models.CharField(blank=True, choices=[('No', 'Нет'), ('Yes', 'Да'), ('mini-PLC', 'mini-PLC'), ('SequenceProgramming', 'Программирование последовательности')], max_length=200, null=True, verbose_name='Встроенный ПЛК'),
        ),
        migrations.AlterField(
            model_name='series',
            name='choke_dc_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Дроссель в звене постоянного тока'),
        ),
        migrations.AlterField(
            model_name='series',
            name='control_panel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Панель управления'),
        ),
        migrations.AlterField(
            model_name='series',
            name='control_panel_included',
            field=models.BooleanField(blank=True, null=True, verbose_name='Панель управления в комплекте'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='series',
            name='digital_inputs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дискретные входы'),
        ),
        migrations.AlterField(
            model_name='series',
            name='emc_filter',
            field=models.CharField(blank=True, choices=[('No', 'Нет'), ('C3', 'C3'), ('C2', 'C2'), ('No_C2', 'Нет/C2')], max_length=10, null=True, verbose_name='Встроенный EMC фильтр'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='series',
            name='operating_temp',
            field=models.CharField(blank=True, choices=[('-10...+40', '-10...+40'), ('-10...+50', '-10...+50'), ('-15...+50', '-15...+50'), ('-20...+50', '-20...+50')], max_length=200, null=True, verbose_name='Рабочая температура'),
        ),
        migrations.AlterField(
            model_name='series',
            name='overload_capacity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Перегрузочная способность'),
        ),
        migrations.AlterField(
            model_name='series',
            name='protection_degree',
            field=models.CharField(blank=True, choices=[('IP20', 'IP20'), ('IP21', 'IP21'), ('IP55', 'IP55')], max_length=200, null=True, verbose_name='Степень защиты'),
        ),
        migrations.AlterField(
            model_name='series',
            name='relay_outputs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Релейные выходы'),
        ),
        migrations.AlterField(
            model_name='series',
            name='transistor_outputs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Транзисторные выходы'),
        ),
    ]
