# Generated by Django 4.0.6 on 2022-09-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0024_alter_series_different_engines_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='control_built_in_fan',
        ),
        migrations.AlterField(
            model_name='series',
            name='engine_protection',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Перегрузка по току, перенапряжение, перегрев, потеря фазы')], null=True, verbose_name='Защита двигателя'),
        ),
    ]
