# Generated by Django 4.0.6 on 2022-09-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0024_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='overload_capacity',
            field=models.TextField(blank=True, null=True, verbose_name='Перегрузочная способность'),
        ),
    ]
