# Generated by Django 4.0.6 on 2022-09-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0025_alter_series_overload_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='maximum_output_frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальная выходная частота, Гц'),
        ),
    ]
