# Generated by Django 4.0.6 on 2022-09-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0026_series_maximum_output_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='starting_torque',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пусковой момент'),
        ),
    ]
