# Generated by Django 4.0.6 on 2022-09-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0026_remove_series_overcurrent_protection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='stop_prevention',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Предотвращение зависания при разгоне, замедлении и работе')], null=True, verbose_name='Предотвращение зависания'),
        ),
    ]
