# Generated by Django 4.0.6 on 2022-09-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0027_alter_series_stop_prevention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='automatic_start_after_power_loss',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Время задаётся в пределах 0...20с')], null=True, verbose_name='Автоматический запуск после пропадания питания'),
        ),
    ]
