# Generated by Django 4.0.6 on 2022-09-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0027_series_starting_torque'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='setting_vf_characteristic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Задание характеристики V/F'),
        ),
    ]
