# Generated by Django 4.0.6 on 2022-09-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0028_alter_series_automatic_start_after_power_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='current_leakage_protection',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Уровень тока утечки более 50% от номинального тока ПЧ')], null=True, verbose_name='Защита от утечек тока на землю'),
        ),
    ]
