# Generated by Django 4.0.6 on 2022-09-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0029_series_speed_control_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='torque_limitation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ограничение момента'),
        ),
    ]
