# Generated by Django 4.0.6 on 2022-09-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0029_alter_series_current_leakage_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='control_panel_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание панели управления'),
        ),
        migrations.AlterField(
            model_name='series',
            name='control_panel',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='Панель управления'),
        ),
    ]
