# Generated by Django 4.0.6 on 2022-09-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0030_series_torque_limitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='torque_accuracy',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Точность по моменту'),
        ),
    ]
