# Generated by Django 4.0.6 on 2022-09-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0031_alter_series_control_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='power_outages',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Да')], null=True, verbose_name='Преодоление провалов напряжения'),
        ),
    ]
