# Generated by Django 4.0.6 on 2022-09-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0031_series_torque_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='maximum_output_frequency',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Максимальная выходная частота'),
        ),
    ]
