# Generated by Django 4.0.6 on 2022-09-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0032_alter_series_maximum_output_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='control_methods',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Методы управления'),
        ),
    ]
