# Generated by Django 4.0.6 on 2022-09-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0032_alter_series_power_outages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='power_outages',
            field=models.BooleanField(blank=True, null=True, verbose_name='Преодоление провалов напряжения'),
        ),
        migrations.AlterField(
            model_name='series',
            name='pulse_frequency_setting',
            field=models.BooleanField(blank=True, null=True, verbose_name='Импульсное задание частоты'),
        ),
    ]
