# Generated by Django 4.0.6 on 2022-09-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0033_series_control_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='output_frequency_accuracy',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Точность выходной частоты'),
        ),
    ]
