# Generated by Django 4.0.6 on 2022-09-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0034_series_output_frequency_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='frequency_set_discreteness',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дискретность задания частоты'),
        ),
    ]
