# Generated by Django 4.0.6 on 2022-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0035_remove_series_realtime_clock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='external_power_24v',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Опциональная плата')], null=True, verbose_name='Подключение внешнего питания +24В'),
        ),
    ]
