# Generated by Django 4.0.6 on 2022-09-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0035_series_frequency_set_discreteness'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='frequency_set_signals',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Сигналы задания частоты'),
        ),
    ]
