# Generated by Django 4.0.6 on 2022-09-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0036_series_frequency_set_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='acceleration_deceleration_time',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Время разгона/торможения'),
        ),
    ]
