# Generated by Django 4.0.6 on 2022-09-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0037_series_acceleration_deceleration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='main_control_functions',
            field=models.TextField(blank=True, null=True, verbose_name='Основные функции управления'),
        ),
    ]
