# Generated by Django 4.0.6 on 2022-09-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0037_alter_series_protection_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='choke_dc_link',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'C3'), (2, 'C2')], null=True, verbose_name='Дроссель в звене постоянного тока'),
        ),
    ]
