# Generated by Django 4.0.6 on 2022-09-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0038_series_main_control_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='control_built_in_fan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Управление встроенным вентилятором охлаждения'),
        ),
    ]
