# Generated by Django 4.0.6 on 2022-09-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0039_series_control_built_in_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='engine_protection',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Защита двигателя'),
        ),
    ]
