# Generated by Django 4.0.6 on 2022-09-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0040_series_engine_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='automatic_start_after_power_loss',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Автоматический запуск после пропадания питания'),
        ),
        migrations.AddField(
            model_name='series',
            name='current_leakage_protection',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Защита от утечек тока на землю'),
        ),
        migrations.AddField(
            model_name='series',
            name='overcurrent_protection',
            field=models.TextField(blank=True, null=True, verbose_name='Защита от перегрузки по току'),
        ),
        migrations.AddField(
            model_name='series',
            name='overvoltage_protection',
            field=models.TextField(blank=True, null=True, verbose_name='Защита по превышению напряжения'),
        ),
        migrations.AddField(
            model_name='series',
            name='stop_prevention',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предотвращение остановки'),
        ),
        migrations.AddField(
            model_name='series',
            name='temperature_protection',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Защита по температуре'),
        ),
    ]
