# Generated by Django 4.0.6 on 2022-09-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0040_alter_series_brake_interrupter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='brake_interrupter',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Встроен на мощности до 37 кВт'), (2, 'Встроен')], null=True, verbose_name='Тормозной прерыватель'),
        ),
        migrations.AlterField(
            model_name='series',
            name='motor_cable_length',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Без дросселя: экран.кабель 35...100м в зависимости от номинала; неэкран. 50...150м. С дросселем: экран.кабель 50...150м; неэкран. 90...225м'), (2, 'Без дросселя: экран.кабель 50...150м в зависимости от номинала; неэкран. 75...225м. С дросселем: экран.кабель 75...225м; неэкран. 115...325м')], null=True, verbose_name='Максимальная длина кабеля двигателя'),
        ),
    ]
