# Generated by Django 4.0.6 on 2022-09-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0041_series_automatic_start_after_power_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='overvoltage_protection',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Защита по превышению напряжения'),
        ),
    ]
