# Generated by Django 4.0.6 on 2022-09-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0041_alter_series_brake_interrupter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='analog_inputs',
        ),
        migrations.RemoveField(
            model_name='series',
            name='analog_outputs',
        ),
        migrations.RemoveField(
            model_name='series',
            name='digital_inputs',
        ),
        migrations.RemoveField(
            model_name='series',
            name='relay_outputs',
        ),
        migrations.RemoveField(
            model_name='series',
            name='transistor_outputs',
        ),
        migrations.AddField(
            model_name='series',
            name='inputs_outputs',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Уровень тока утечки более 50% от номинального тока ПЧ')], null=True, verbose_name='Входы/выходы'),
        ),
    ]
