# Generated by Django 4.0.6 on 2022-09-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0042_alter_series_overvoltage_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='atmospheric_pressure_transportation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Атмосферное давление при транспортировке'),
        ),
        migrations.AddField(
            model_name='series',
            name='atmospheric_pressure_use_storage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Атмосферное давление при эксплуатации/хранении'),
        ),
        migrations.AddField(
            model_name='series',
            name='impact_resistance',
            field=models.TextField(blank=True, null=True, verbose_name='Ударопрочность'),
        ),
        migrations.AddField(
            model_name='series',
            name='installation_altitude',
            field=models.TextField(blank=True, null=True, verbose_name='Высота установки'),
        ),
        migrations.AddField(
            model_name='series',
            name='installation_place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место установки'),
        ),
        migrations.AddField(
            model_name='series',
            name='mounting_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Положение монтажа'),
        ),
        migrations.AddField(
            model_name='series',
            name='pollution_level_storage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Уровень загрязнения при хранении'),
        ),
        migrations.AddField(
            model_name='series',
            name='pollution_level_transportation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Уровень загрязнения при транспортировке'),
        ),
        migrations.AddField(
            model_name='series',
            name='pollution_level_use',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Уровень загрязнения при эксплуатации'),
        ),
        migrations.AddField(
            model_name='series',
            name='storage_temp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Температура хранения'),
        ),
        migrations.AddField(
            model_name='series',
            name='storage_transportation_relative_humidity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Относительная влажность при хранении/транспортировке'),
        ),
        migrations.AddField(
            model_name='series',
            name='transport_temp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Температура транспортировки'),
        ),
        migrations.AddField(
            model_name='series',
            name='use_relative_humidity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Относительная влажность при эксплуатации'),
        ),
        migrations.AddField(
            model_name='series',
            name='vibration',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вибрация'),
        ),
    ]
