# Generated by Django 4.0.6 on 2022-09-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0043_alter_series_inputs_outputs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='installation_place',
        ),
        migrations.AlterField(
            model_name='series',
            name='inputs_outputs',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Дискретные входы: 7; Аналоговые входы: 2; Транзисторные выходы: 3; Релейные выходы: 1; Аналоговые выходы: 1'), (2, 'Дискретные входы: 10; Аналоговые входы: 3; Транзисторные выходы: 0; Релейные выходы: 3; Аналоговые выходы: 2')], null=True, verbose_name='Входы/выходы'),
        ),
    ]
