# Generated by Django 4.0.6 on 2022-09-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0044_alter_series_atmospheric_pressure_transportation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='operating_temp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Рабочая температура, ℃'),
        ),
        migrations.AlterField(
            model_name='series',
            name='storage_temp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Температура хранения, ℃'),
        ),
        migrations.AlterField(
            model_name='series',
            name='transport_temp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Температура транспортировки, ℃'),
        ),
    ]
