# Generated by Django 4.0.6 on 2022-09-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0045_alter_series_operating_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='wall_to_wall_installation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Монтаж "Стенка к стенке"'),
        ),
    ]
