# Generated by Django 4.0.6 on 2022-09-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0045_remove_series_vibration_alter_series_operating_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='copy_backup_settings',
            field=models.BooleanField(blank=True, null=True, verbose_name='Копирование/бэкап настроек'),
        ),
    ]
