# Generated by Django 4.0.6 on 2022-09-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0046_series_wall_to_wall_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='motor_cable_length',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Длина кабеля двигателя'),
        ),
    ]
