# Generated by Django 4.0.6 on 2022-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0047_series_motor_cable_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='motor_cable_length',
            field=models.TextField(blank=True, null=True, verbose_name='Максимальная длина кабеля двигателя'),
        ),
    ]
