# Generated by Django 4.0.6 on 2022-09-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0048_alter_series_motor_cable_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='control_panel_at_distance',
            field=models.BooleanField(blank=True, null=True, verbose_name='Возможность выносного крепления панели'),
        ),
    ]
