# Generated by Django 4.0.6 on 2022-09-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0049_series_control_panel_at_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='control_panel_at_distance',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Возможность выносного крепления панели'),
        ),
    ]
