# Generated by Django 4.0.6 on 2022-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0050_alter_series_control_panel_at_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='control_panel',
            field=models.TextField(blank=True, null=True, verbose_name='Панель управления'),
        ),
    ]
