# Generated by Django 4.0.6 on 2022-09-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0050_series_motors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='operating_temp',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '-10...+40'), (2, '-10...+40(+50); \nСо снижением характеристик -10...+60'), (3, '-20...+50; \nСо снижением характеристик -20...+60')], null=True, verbose_name='Рабочая температура, ℃'),
        ),
    ]
