# Generated by Django 4.0.6 on 2022-09-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0051_alter_series_control_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='encoder_support',
            field=models.BooleanField(default=False, verbose_name='Поддержка обратной связи от энкодера'),
        ),
        migrations.AlterField(
            model_name='series',
            name='built_in_communication',
            field=models.CharField(blank=True, choices=[('No', 'Нет'), ('ModBusRTU', 'Modbus RTU'), ('ModBusRTU/BACnet', 'Modbus RTU, BACnet')], max_length=200, null=True, verbose_name='Встроенный протокол связи'),
        ),
    ]
