# Generated by Django 4.0.6 on 2022-09-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0051_alter_series_operating_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='installation_altitude',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '<1000м'), (2, '<1000м; >1000м со снижением характеристик')], null=True, verbose_name='Высота установки'),
        ),
    ]
