# Generated by Django 4.0.6 on 2022-09-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0052_alter_series_installation_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='installation_altitude',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'До 1000м'), (2, 'До 1000м; Свыше 1000м со снижением характеристик')], null=True, verbose_name='Высота установки'),
        ),
    ]
