# Generated by Django 4.0.6 on 2022-09-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0052_series_encoder_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='pre_configurations',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предварительные конфигурации'),
        ),
        migrations.AlterField(
            model_name='series',
            name='additional_communications',
            field=models.CharField(blank=True, choices=[('No', 'Нет'), ('Expansion cards', 'Да, платы расширения'), ('ModBusRTU', 'RS-485 Modbus RTU'), ('DeviceNet, Ethernet, CANopen, ProfibusDP', 'DeviceNet, Ethernet, CANopen, ProfibusDP'), ('CANopen', 'CANopen')], max_length=200, null=True, verbose_name='Дополнительные протоколы связи'),
        ),
    ]
