# Generated by Django 4.0.6 on 2022-09-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0053_alter_series_installation_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='motor_cable_length',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Без дросселя: до 50м; С дросселем: до 100м'), (2, 'Без дросселя: экран.кабель 35...100м в зависимости от номинала; неэкран. 50...150м. \nС дросселем: экран.кабель 50...150м; неэкран. 90...225м'), (3, 'Без дросселя: экран.кабель 50...150м в зависимости от номинала; неэкран. 75...225м. \nС дросселем: экран.кабель 75...225м; неэкран. 115...325м')], null=True, verbose_name='Максимальная длина кабеля двигателя'),
        ),
    ]
