# Generated by Django 4.0.6 on 2022-09-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0054_series_copy_backup_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='engine_cascade_control',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Управление каскадом двигателей'),
        ),
    ]
