# Generated by Django 4.0.6 on 2022-09-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0054_alter_series_motor_cable_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='maximum_output_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '320'), (2, '599 Гц; 90 кВт и выше: 400 Гц'), (3, '599')], null=True, verbose_name='Максимальная выходная частота, Гц'),
        ),
    ]
