# Generated by Django 4.0.6 on 2022-09-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0055_series_engine_cascade_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='multi_pump_system',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Система Multi-pump (группа приводов-насосов подключенных по шине)'),
        ),
    ]
