# Generated by Django 4.0.6 on 2022-09-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0056_series_multi_pump_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='pid_controller',
            field=models.IntegerField(blank=True, null=True, verbose_name='Встроенный ПИД-регулятор'),
        ),
        migrations.AlterField(
            model_name='series',
            name='encoder_support',
            field=models.BooleanField(default=False, verbose_name='Подключение энкодера'),
        ),
    ]
