# Generated by Django 4.0.6 on 2022-09-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0058_alter_series_pid_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='pid_controller',
            field=models.IntegerField(blank=True, null=True, verbose_name='Встроенный ПИД-регулятор'),
        ),
    ]
