# Generated by Django 4.0.6 on 2022-09-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0059_alter_series_stop_prevention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='stop_prevention',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Токоограничение при разгоне, замедлении и работе (общая настройка)'), (2, 'Токоограничение при разгоне, замедлении и работе (независимые настройки)')], null=True, verbose_name='Предотвращение перегрузки'),
        ),
    ]
