# Generated by Django 4.0.6 on 2022-09-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0059_alter_series_pid_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='fire_mode',
            field=models.BooleanField(blank=True, null=True, verbose_name='Пожарный режим'),
        ),
    ]
