# Generated by Django 4.0.6 on 2022-09-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0061_alter_series_copy_backup_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='circuit_boards_protection',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Специальное покрытие печатных плат для повышения надёжности в критических условиях'),
        ),
    ]
