# Generated by Django 4.0.6 on 2022-09-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0062_alter_series_automatic_start_after_power_loss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='power_outages',
        ),
    ]
