# Generated by Django 4.0.6 on 2022-09-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0062_series_circuit_boards_protection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='circuit_boards_protection',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Защита печатных плат'),
        ),
    ]
