# Generated by Django 4.0.6 on 2022-09-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0063_alter_series_circuit_boards_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='flying_start',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подхват на ходу'),
        ),
        migrations.AddField(
            model_name='series',
            name='skip_frequency',
            field=models.BooleanField(blank=True, null=True, verbose_name='Пропуск критических частот'),
        ),
        migrations.AddField(
            model_name='series',
            name='sleep_mode',
            field=models.BooleanField(blank=True, null=True, verbose_name='Спящий режим'),
        ),
    ]
