# Generated by Django 4.0.6 on 2022-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0063_remove_series_power_outages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='current_leakage_protection',
        ),
        migrations.AlterField(
            model_name='series',
            name='automatic_start_after_power_loss',
            field=models.BooleanField(blank=True, null=True, verbose_name='Преодоление провалов напряжения питания'),
        ),
    ]
