# Generated by Django 4.0.6 on 2022-09-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0064_series_flying_start_series_skip_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='built_in_plc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Встроенный ПЛК'),
        ),
    ]
