# Generated by Django 4.0.6 on 2022-09-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0064_remove_series_current_leakage_protection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='external_power_24v',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Опциональная плата')], null=True, verbose_name='Подключение внешнего питания +24В'),
        ),
    ]
