# Generated by Django 4.0.6 on 2022-09-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0065_alter_series_external_power_24v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencydrive',
            name='power',
            field=models.FloatField(verbose_name='Мощность'),
        ),
    ]
