# Generated by Django 4.0.6 on 2022-09-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0065_alter_series_built_in_plc'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='realtime_clock',
            field=models.BooleanField(blank=True, null=True, verbose_name='Часы реального времени'),
        ),
    ]
