# Generated by Django 4.0.6 on 2022-09-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0066_series_realtime_clock'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='quick_change_fans',
            field=models.BooleanField(blank=True, null=True, verbose_name='Быстро-заменяемые вентиляторы'),
        ),
    ]
