# Generated by Django 4.0.6 on 2022-09-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplier_country_delete_brand_and_more'),
        ('vfd', '0066_alter_frequencydrive_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.country', verbose_name='Страна'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
