# Generated by Django 4.0.6 on 2022-09-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_equipmentline'),
        ('vfd', '0067_alter_brand_country_alter_supplier_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipmentLine',
        ),
        migrations.AlterField(
            model_name='brand',
            name='equipment_lines',
            field=models.ManyToManyField(to='supplier.equipmentline', verbose_name='Линейки оборудования'),
        ),
    ]
