# Generated by Django 4.0.6 on 2022-09-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0067_series_quick_change_fans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='quick_change_fans',
            field=models.BooleanField(blank=True, null=True, verbose_name='Быстрозаменяемые вентиляторы'),
        ),
    ]
