# Generated by Django 4.0.6 on 2022-09-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplier'),
        ('vfd', '0068_delete_equipmentline_alter_brand_equipment_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='suppliers',
            field=models.ManyToManyField(to='supplier.supplier', verbose_name='Поставщики'),
        ),
        migrations.AlterField(
            model_name='price',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Поставщик'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
