# Generated by Django 4.0.6 on 2022-09-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_brand'),
        ('vfd', '0069_alter_brand_suppliers_alter_price_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.brand', verbose_name='Бренд'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
