# Generated by Django 4.0.6 on 2022-09-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0069_series_automatic_energy_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='additional_communications',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнительные протоколы связи'),
        ),
    ]
