# Generated by Django 4.0.6 on 2022-09-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0070_alter_series_additional_communications'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='io_expansion_boards',
            field=models.BooleanField(blank=True, null=True, verbose_name='Платы расширения входов-выходов'),
        ),
    ]
