# Generated by Django 4.0.6 on 2022-09-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0071_series_io_expansion_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='removable_terminal_blocks',
            field=models.BooleanField(blank=True, null=True, verbose_name='Съёмные клеммные колодки'),
        ),
    ]
