# Generated by Django 4.0.6 on 2022-09-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0071_alter_series_power_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='power_range',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1x220В: 0.4...2.2кВт; 3x380В: 0.75...3.7кВт'), (2, '1x220В: 0.4...2.2кВт; 3x380В: 0.75...15кВт'), (3, '1x220В: 0.2...2.2кВт; 3x380В: 0.4...22кВт'), (4, '0.75...500кВт'), (5, '1x220В: 0.4...2.2кВт; 3x380В: 0.75...630кВт')], null=True, verbose_name='Диапазон мощностей'),
        ),
    ]
