# Generated by Django 4.0.6 on 2022-09-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0073_alter_series_power_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='power_range',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...3.7кВт'), (20, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...15кВт'), (30, '1x230В: 0.2...2.2кВт; 3x400В: 0.4...22кВт'), (40, '3x400В: 0.75...500кВт'), (41, '3x400В: 0.75...630кВт'), (42, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...630кВт')], null=True, verbose_name='Диапазон мощностей'),
        ),
    ]
