# Generated by Django 4.0.6 on 2022-09-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0073_alter_series_quick_change_fans'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='dual_circuit_cooling',
            field=models.BooleanField(blank=True, null=True, verbose_name='Двухконтурное охлаждение'),
        ),
    ]
