# Generated by Django 4.0.6 on 2022-09-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0074_alter_series_power_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='control_methods',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'V/F (скалярное управление), \nSVC (бездатчиковое векторное управление)'), (11, 'V/F (скалярное управление), \nFVC (бездатчиковое векторное управление)'), (20, 'V/F (скалярное управление), \nSVC (бездатчиковое векторное управление), \nVC (векторное управление в замкнутом контуре)')], null=True, verbose_name='Методы управления'),
        ),
    ]
