# Generated by Django 4.0.6 on 2022-09-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0074_series_dual_circuit_cooling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='operating_temp',
            field=models.TextField(blank=True, null=True, verbose_name='Рабочая температура, ℃'),
        ),
    ]
