# Generated by Django 4.0.6 on 2022-09-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0076_alter_series_control_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='brake_interrupter',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Встроен на мощности до 15 кВт'), (2, 'Встроен на мощности до 37 кВт'), (3, 'Встроен')], null=True, verbose_name='Тормозной прерыватель'),
        ),
    ]
