# Generated by Django 4.0.6 on 2022-09-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0080_alter_series_choke_dc_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='overload_capacity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Лёгкий режим: 120% 60с; \nНормальный режим: 120% 60с, 160% 3с'), (20, '150% 60с; 180% 3с'), (21, 'G Model: 150% 60с, 180% 3с; \nP Model: 120% 60с, 150% 3с'), (30, 'Нормальный режим: 120% 60с, 150% 3с; \nТяжелый режим: 150% 60с, 200% 3с')], null=True, verbose_name='Перегрузочная способность'),
        ),
    ]
