# Generated by Django 4.0.6 on 2022-09-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0085_alter_series_inputs_outputs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='additional_communications',
        ),
        migrations.RemoveField(
            model_name='series',
            name='built_in_communication',
        ),
        migrations.AddField(
            model_name='series',
            name='communications',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Плата расширения: Modbus RTU'), (20, 'Встроен: Modbus RTU'), (30, 'Встроен: Modbus RTU; Платы расширения: DeviceNet, Ethernet IP, Modbus TCP, CANopen, Profibus DP'), (40, 'Встроены: Modbus RTU, BACnet; Платы расширения: DeviceNet, Ethernet IP, Modbus TCP, CANopen, Profibus DP')], null=True, verbose_name='Протоколы связи'),
        ),
    ]
