# Generated by Django 4.0.6 on 2022-09-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0088_alter_series_encoder_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='control_panel',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'LED 4x7'), (2, 'LED 5x7'), (3, 'LED 5x7 (LCD опционально)'), (4, 'LCD дисплей')], null=True, verbose_name='Панель управления'),
        ),
    ]
