# Generated by Django 4.0.6 on 2022-09-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0089_alter_series_control_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='multi_pump_system',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Нет'), (2, 'Да, 2 насоса'), (3, 'Да, до 4 насосов'), (4, 'Да, до 8 насосов')], null=True, verbose_name='Много-насосный режим'),
        ),
    ]
