# Generated by Django 4.0.6 on 2022-09-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0090_alter_series_multi_pump_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='skip_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Пропуск 2-х полос частот'), (2, 'Пропуск 3-х полос частот')], null=True, verbose_name='Пропуск критических частот'),
        ),
    ]
