# Generated by Django 4.0.6 on 2022-09-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0093_alter_series_engine_cascade_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='external_power_24v',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Опциональная плата'), (2, 'Да')], null=True, verbose_name='Подключение внешнего питания +24В'),
        ),
    ]
