# Generated by Django 4.0.6 on 2022-09-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0096_alter_series_communications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='pre_configurations',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (1, 'Группировка параметров по применениям')], null=True, verbose_name='Предварительные конфигурации (Макросы)'),
        ),
    ]
