# Generated by Django 4.0.6 on 2022-09-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0098_alter_series_wall_to_wall_installation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='atmospheric_pressure_use',
        ),
    ]
