# Generated by Django 4.0.6 on 2022-09-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0099_remove_series_atmospheric_pressure_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='control_panel',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'LED 4x7'), (20, 'LED 5x7'), (30, 'LED двухстрочный'), (31, 'LED 5x7 (LCD опционально)'), (40, 'LCD дисплей')], null=True, verbose_name='Панель управления'),
        ),
    ]
