# Generated by Django 4.0.6 on 2022-09-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0100_alter_series_control_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='pre_configurations',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Группировка параметров по применениям'), (11, 'Макросы')], null=True, verbose_name='Предварительные конфигурации (Макросы)'),
        ),
    ]
