# Generated by Django 4.0.6 on 2022-09-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0106_alter_series_starting_torque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='operating_temp',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '-10...+40'), (2, '-10...+40; \nСо снижением характеристик -10...+50'), (3, '-10...+40(+50); \nСо снижением характеристик -10...+60'), (4, '-20...+50; \nСо снижением характеристик -20...+60')], null=True, verbose_name='Рабочая температура, ℃'),
        ),
    ]
