# Generated by Django 4.0.6 on 2022-09-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0109_alter_series_skip_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='stop_prevention',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Токоограничение при разгоне, замедлении и работе (общая настройка)'), (20, 'Токоограничение при разгоне, замедлении и работе (независимые настройки)'), (21, 'Токоограничение при разгоне, работе (независимые настройки)')], null=True, verbose_name='Предотвращение перегрузки'),
        ),
    ]
