# Generated by Django 4.0.6 on 2022-09-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0111_alter_series_power_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='inputs_outputs',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'DI: 4; AI: 1; TO: 0; RO: 1; AO: 1'), (20, 'DI: 4; AI: 2; TO: 0; RO: 1; AO: 1'), (30, 'DI: 5; AI: 1; TO: 1; RO: 1; AO: 1'), (40, 'DI: 6; AI: 2; TO: 0; RO: 1; AO: 1'), (50, 'DI: 6; AI: 2; TO: 1; RO: 2; AO: 2'), (60, 'DI: 7; AI: 2; TO: 3; RO: 1; AO: 1'), (61, 'DI: 7; AI: 2; TO: 2; RO: 2; AO: 1'), (70, 'DI: 10; AI: 3; TO: 0; RO: 3; AO: 2')], null=True, verbose_name='Входы/выходы'),
        ),
        migrations.AlterField(
            model_name='series',
            name='overload_capacity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Лёгкий режим: 120% 60с; \nНормальный режим: 120% 60с, 160% 3с'), (20, '150% 60с; 180% 3с'), (21, 'G Model: 150% 60с, 180% 3с; \nP Model: 120% 60с, 150% 3с'), (30, '110% длит.; 150% 60с; 180% 5с'), (31, 'Нормальный режим: 120% 60с, 150% 3с; \nТяжелый режим: 150% 60с, 200% 3с'), (32, '150% 60с; 200% 4с')], null=True, verbose_name='Перегрузочная способность'),
        ),
    ]
