# Generated by Django 4.0.6 on 2022-09-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0115_alter_series_maximum_output_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='circuit_boards_protection',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Специальное покрытие печатных плат'), (11, 'Трёхслойное защитное покрытие')], null=True, verbose_name='Защита печатных плат'),
        ),
    ]
