# Generated by Django 4.0.6 on 2022-09-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0116_alter_series_circuit_boards_protection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='emc_filter',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, '1x230В: C3; 3x400В: контур ЭМС-фильтра'), (11, 'контур ЭМС-фильтра'), (20, 'C3'), (30, 'C2')], null=True, verbose_name='Встроенный EMC фильтр'),
        ),
    ]
