# Generated by Django 4.0.6 on 2022-09-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0117_alter_series_emc_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='emc_filter',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, '1x230В: C3; 3x400В: контур ЭМС-фильтра'), (11, 'Контур ЭМС-фильтра'), (20, 'C3'), (30, 'C2')], null=True, verbose_name='Встроенный EMC фильтр'),
        ),
        migrations.AlterField(
            model_name='series',
            name='overload_capacity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Лёгкий режим: 120% 60с; \nНормальный режим: 120% 60с, 160% 3с'), (20, '150% 60с; 180% 3с'), (21, 'G type: 150% 60с, 180% 3с; \nP type: 120% 60с, 150% 3с'), (30, '110% длит.; 150% 60с; 180% 5с'), (31, 'Нормальный режим: 120% 60с, 150% 3с; \nТяжелый режим: 150% 60с, 200% 3с'), (32, 'G type: 110% длит.; 150% 60с, 200% 4с; \nP type: 105% длит.; 120% 60с, 150% 1с;')], null=True, verbose_name='Перегрузочная способность'),
        ),
        migrations.AlterField(
            model_name='series',
            name='starting_torque',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '150% / 0.5 Гц'), (11, 'G type: 150% / 0.5 Гц (SVC)'), (12, 'G type: 150% / 0.5 Гц (SVC);\nP type: 100% / 0.5 Гц'), (13, '150% / 3 Гц (V/F), \n150% / 1 Гц (FVC)'), (14, '150% / 3 Гц (V/F, SVC для IM в тяжёлом режиме)\n100% / 2.5 Гц (V/F, SVC для PM в тяжёлом режиме)'), (15, '100% / 0.5 Гц (V/F); 150% / 0.5 Гц (SVC)'), (16, '150% / 0.5 Гц (SVC)'), (20, 'G type: 150% / 0.5 Гц (SVC), 180% / 0 Гц (VC);\nP type: 100% / 0.5 Гц')], null=True, verbose_name='Пусковой момент'),
        ),
    ]
