# Generated by Django 4.0.6 on 2022-09-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0118_alter_series_emc_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='brake_interrupter',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Встроен на мощности до 15 кВт'), (20, 'Встроен на мощности до 37 кВт'), (30, 'Встроен на мощности до 45 кВт'), (40, 'Встроен')], null=True, verbose_name='Тормозной прерыватель'),
        ),
        migrations.AlterField(
            model_name='series',
            name='power_range',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...3.7кВт'), (20, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...5.5кВт'), (30, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...15кВт'), (40, '1x230В: 0.2...2.2кВт; 3x400В: 0.4...22кВт'), (50, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...220кВт'), (60, '3x400В: 0.75...500кВт'), (61, '3x400В: 0.75...630кВт'), (62, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...630кВт')], null=True, verbose_name='Диапазон мощностей'),
        ),
        migrations.AlterField(
            model_name='series',
            name='starting_torque',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '150% / 0.5 Гц'), (11, 'G type: 150% / 0.5 Гц (SVC)'), (12, 'G type: 150% / 0.5 Гц (SVC);\nP type: 100% / 0.5 Гц'), (13, '150% / 3 Гц (V/F), \n150% / 1 Гц (FVC)'), (14, '150% / 3 Гц (V/F, SVC для IM в тяжёлом режиме)\n100% / 2.5 Гц (V/F, SVC для PM в тяжёлом режиме)'), (15, '100% / 0.5 Гц (V/F); 150% / 0.5 Гц (SVC)'), (16, '150% / 3(1) Гц (V/F); 150% / 0.5 Гц (SVC)'), (20, 'G type: 150% / 0.5 Гц (SVC), 180% / 0 Гц (VC);\nP type: 100% / 0.5 Гц')], null=True, verbose_name='Пусковой момент'),
        ),
    ]
