# Generated by Django 4.0.6 on 2022-09-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0119_alter_series_brake_interrupter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='engine_cascade_control',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Нет'), (20, 'Да, 2 двигателя'), (30, 'Да, до 3 двигателей'), (40, 'Да, до 4 двигателей'), (50, 'Да, до 8 двигателей')], null=True, verbose_name='Управление каскадом двигателей'),
        ),
        migrations.AlterField(
            model_name='series',
            name='multi_pump_system',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Нет'), (20, 'Да, 2 насоса'), (30, 'Да, до 3 насосов'), (40, 'Да, до 4 насосов'), (50, 'Да, до 8 насосов')], null=True, verbose_name='Много-насосный режим'),
        ),
    ]
