# Generated by Django 4.0.6 on 2022-09-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0122_alter_series_external_power_24v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='overload_capacity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Лёгкий режим: 120% 60с; \nНормальный режим: 120% 60с, 160% 3с'), (20, '150% 60с; 180% 3с'), (21, 'G type: 150% 60с, 180% 3с; \nP type: 120% 60с, 150% 3с'), (22, '150% 60с; 180% 2с; 200% 0.5c'), (30, '110% длит.; 150% 60с; 180% 5с'), (31, 'Нормальный режим: 120% 60с, 150% 3с; \nТяжелый режим: 150% 60с, 200% 3с'), (32, 'G type: 110% длит.; 150% 60с, 200% 4с; \nP type: 105% длит.; 120% 60с, 150% 1с;')], null=True, verbose_name='Перегрузочная способность'),
        ),
    ]
