# Generated by Django 4.0.6 on 2022-09-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0127_alter_series_stop_prevention'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='pc_soft',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (30, 'Да')], null=True, verbose_name='Софт для отладки на ПК'),
        ),
    ]
