# Generated by Django 4.0.6 on 2022-09-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0129_alter_series_power_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='communications',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Плата расширения: Modbus RTU'), (20, 'Платы расширения: Modbus RTU, Profibus DP'), (30, 'Встроен: Modbus RTU'), (40, 'Встроен: Modbus RTU; Платы расширения: Profibus DP'), (50, 'Встроен: Modbus RTU; Платы расширения: DeviceNet, Ethernet IP, Modbus TCP, CANopen, Profibus DP'), (60, 'Встроены: Modbus RTU, BACnet; Платы расширения: DeviceNet, Ethernet IP, Modbus TCP, CANopen, Profibus DP')], null=True, verbose_name='Протоколы связи'),
        ),
    ]
