# Generated by Django 4.0.6 on 2022-09-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0132_alter_series_inputs_outputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='copy_backup_settings',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (20, 'Да (LCD панель)'), (40, 'Да')], null=True, verbose_name='Копирование/бэкап настроек'),
        ),
    ]
