# Generated by Django 4.0.6 on 2022-09-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0133_alter_series_copy_backup_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='choke_dc_link',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Опция от 75кВт'), (20, 'Опция'), (30, 'Встроен на мощности 11, 15 кВт и от 200 кВт'), (40, 'Встроен на мощности от 45 кВт')], null=True, verbose_name='Дроссель в звене постоянного тока'),
        ),
    ]
