# Generated by Django 4.0.6 on 2022-09-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0134_alter_series_choke_dc_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='operating_temp',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '-10...+40'), (20, '-10...+40; \nСо снижением характеристик -10...+50'), (30, '-10...+40(50); \nСо снижением характеристик -10...+60'), (40, '-20...+50; \nСо снижением характеристик -20...+60'), (50, '-30...+40(50)')], null=True, verbose_name='Рабочая температура, ℃'),
        ),
    ]
