# Generated by Django 4.0.6 on 2022-09-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0139_alter_series_power_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='encoder_support',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Импульсный вход (плата расширения)'), (20, 'Импульсный вход'), (30, 'Плата расширения энкодера (ABZ, UVW, Rotary transformer)'), (31, 'Плата расширения энкодера')], null=True, verbose_name='Подключение энкодера'),
        ),
        migrations.AlterField(
            model_name='series',
            name='maximum_output_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '320'), (20, '599; 90 кВт и выше: 400'), (30, '599'), (31, '600'), (40, '999'), (50, '3000 (V/F); 300 (SVC)'), (51, '3200 (V/F); 300 (SVC)'), (52, '3200 (V/F); 500 (SVC)')], null=True, verbose_name='Максимальная выходная частота, Гц'),
        ),
    ]
