# Generated by Django 4.0.6 on 2022-09-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0140_alter_series_encoder_support_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='choke_dc_link',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Опция от 75кВт'), (20, 'Опция 45...400кВт, встроен от 450кВт'), (30, 'Опция'), (40, 'Встроен на мощности 11, 15 кВт и от 200 кВт'), (50, 'Встроен на мощности от 45 кВт')], null=True, verbose_name='Дроссель в звене постоянного тока'),
        ),
        migrations.AlterField(
            model_name='series',
            name='communications',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Плата расширения: Modbus RTU'), (20, 'Платы расширения: Modbus RTU, Profibus DP'), (30, 'Встроен: Modbus RTU'), (40, 'Встроен: Modbus RTU; Платы расширения: Profibus DP'), (50, 'Встроен: Modbus RTU; Платы расширения: Profibus DP, Ethernet IP'), (60, 'Встроен: Modbus RTU; Платы расширения: DeviceNet, Ethernet IP, Modbus TCP, CANopen, Profibus DP'), (70, 'Встроены: Modbus RTU, BACnet; Платы расширения: DeviceNet, Ethernet IP, Modbus TCP, CANopen, Profibus DP')], null=True, verbose_name='Протоколы связи'),
        ),
    ]
