# Generated by Django 4.0.6 on 2022-09-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0141_alter_series_choke_dc_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='starting_torque',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '150% / 0.5 Гц'), (11, 'G type: 150% / 0.5 Гц (SVC)'), (12, 'G type: 150% / 0.5 Гц (SVC);\nP type: 100% / 0.5 Гц'), (13, '150% / 3 Гц (V/F), \n150% / 1 Гц (FVC)'), (14, '150% / 3 Гц (V/F, SVC для IM в тяжёлом режиме)\n100% / 2.5 Гц (V/F, SVC для PM в тяжёлом режиме)'), (15, '100% / 0.5 Гц (V/F); 150% / 0.5 Гц (SVC)'), (16, '150% / 3(1) Гц (V/F); 150% / 0.5 Гц (SVC)'), (17, 'G type: 150% / 0.5 Гц; \nP type: 100% / 0.5 Гц'), (20, 'G type: 150% / 0.5 Гц (SVC), 180% / 0 Гц (VC);\nP type: 100% / 0.5 Гц')], null=True, verbose_name='Пусковой момент'),
        ),
    ]
