# Generated by Django 4.0.6 on 2022-09-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0144_alter_series_operating_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='brake_interrupter',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Встроен на мощности до 15 кВт'), (20, 'Встроен на мощности до 22 кВт'), (30, 'Встроен на мощности до 30 кВт'), (40, 'Встроен на мощности до 37 кВт'), (50, 'Встроен на мощности до 45 кВт'), (60, 'Встроен')], null=True, verbose_name='Тормозной прерыватель'),
        ),
    ]
