# Generated by Django 4.0.6 on 2022-09-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0146_alter_series_power_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='wall_to_wall_installation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Допускается для ПЧ от 45 кВт включительно; \nДо 45 кВт: зазор 10мм'), (20, 'Допускается при -20...+40℃, \nдо +50℃ со снижением характеристик'), (21, 'Допускается при -20...+40℃')], null=True, verbose_name='Монтаж "Стенка к стенке"'),
        ),
    ]
