# Generated by Django 4.0.6 on 2022-09-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0147_alter_series_wall_to_wall_installation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='control_methods',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'V/F (скалярное управление), \nSVC (бездатчиковое векторное управление)'), (20, 'V/F (скалярное управление), \nSVC (бездатчиковое векторное управление), \nVC (векторное управление с замкнутым контуром)')], null=True, verbose_name='Методы управления'),
        ),
    ]
