# Generated by Django 4.0.6 on 2022-09-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0150_alter_series_carrier_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='carrier_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, '0.5...16'), (31, '2...15'), (32, '2...15 (Default: 4)'), (33, '2...15/10/9 (Default: 8/6/4)')], null=True, verbose_name='Несущая частота ШИМ, кГц'),
        ),
    ]
