# Generated by Django 4.0.6 on 2022-09-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0152_alter_series_carrier_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='choke_dc_link',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Опция от 75кВт'), (20, 'Опция 45...400кВт, встроен от 450кВт'), (30, 'Опция'), (40, 'Встроен на мощности 11, 15 кВт и от 200 кВт'), (50, 'Встроен на мощности от 45 кВт'), (60, 'Встроен')], null=True, verbose_name='Дроссель в звене постоянного тока'),
        ),
        migrations.AlterField(
            model_name='series',
            name='operating_temp',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '-10...+40'), (20, '-10...+40; \nСо снижением характеристик -10...+50'), (21, '-10...+40(50)'), (30, '-10...+40(50); \nСо снижением характеристик -10...+60'), (40, '-10...+50; \nСо снижением характеристик -10...+60'), (50, '-20...+50; \nСо снижением характеристик -20...+60')], null=True, verbose_name='Рабочая температура, ℃'),
        ),
        migrations.AlterField(
            model_name='series',
            name='power_range',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...3.7кВт'), (20, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...5.5кВт'), (30, '1x230В: 0.2...2.2кВт; 3x400В: 0.4...7.5кВт'), (40, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...15кВт'), (50, '1x230В: 0.2...2.2кВт; 3x400В: 0.4...22кВт'), (60, '3x400В: 0.75...37кВт'), (70, '3x400В: 0.75...90кВт'), (80, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...220кВт'), (81, '1x230В: 0.75...2.2кВт; 3x400В: 0.75...220кВт'), (90, '3x400В: 0.75...500кВт'), (91, '3x400В: 0.75...630кВт'), (92, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...630кВт'), (93, '1x230В: 0.75...2.2кВт; 3x400В: 0.75...630кВт')], null=True, verbose_name='Диапазон мощностей'),
        ),
        migrations.AlterField(
            model_name='series',
            name='wall_to_wall_installation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Допускается для ПЧ от 45 кВт включительно; \nДо 45 кВт: зазор 10мм'), (20, 'Допускается при -20...+40℃, \nдо +50℃ со снижением характеристик'), (21, 'Допускается при -20...+40℃'), (30, 'Допускается')], null=True, verbose_name='Монтаж "Стенка к стенке"'),
        ),
    ]
