# Generated by Django 4.0.6 on 2022-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0155_alter_series_control_panel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='carrier_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, '0.5...16'), (31, '2...15'), (32, '2...15 (Default: 4)'), (33, '2...15/10/9 (Default: 8/6/4)'), (34, '2...16 (Default: 4/3)'), (35, '1...16/10/5 (Default: 6/4.5/3/1.8)'), (36, '2...12 (Default: 3)'), (37, '1...14 (Default: 8)')], null=True, verbose_name='Несущая частота ШИМ, кГц'),
        ),
        migrations.AlterField(
            model_name='series',
            name='communications',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Плата расширения: Modbus RTU'), (20, 'Платы расширения: Modbus RTU, Profibus DP'), (30, 'Встроен: Modbus RTU'), (40, 'Встроен: Modbus RTU; Платы расширения: Profibus DP'), (50, 'Встроен: Modbus RTU; Платы расширения: Profibus DP, Ethernet IP'), (60, 'Встроен: Modbus RTU; Платы расширения: Profibus DP, CANlink, CANopen'), (70, 'Встроен: Modbus RTU; Платы расширения: DeviceNet, Ethernet IP, Modbus TCP, CANopen, Profibus DP'), (80, 'Встроены: Modbus RTU, BACnet; Платы расширения: DeviceNet, Ethernet IP, Modbus TCP, CANopen, Profibus DP')], null=True, verbose_name='Протоколы связи'),
        ),
        migrations.AlterField(
            model_name='series',
            name='motor_cable_length',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Без дросселя: до 50м; С дросселем: до 100м'), (20, 'Если длина кабелей двигателя превышает 100 м, рекомендуется использовать моторный дроссель.'), (30, 'Без дросселя: экран.кабель 35...100м в зависимости от номинала; неэкран. 50...150м. \nС дросселем: экран.кабель 50...150м; неэкран. 90...225м'), (40, 'Без дросселя: экран.кабель 50...150м в зависимости от номинала; неэкран. 75...225м. \nС дросселем: экран.кабель 75...225м; неэкран. 115...325м')], null=True, verbose_name='Максимальная длина кабеля двигателя'),
        ),
    ]
