# Generated by Django 4.0.6 on 2022-09-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0157_alter_series_maximum_output_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='engine_cascade_control',
        ),
        migrations.AlterField(
            model_name='series',
            name='carrier_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(31, '2...15'), (32, '2...15 (Default: 4)'), (33, '2...15/10/9 (Default: 8/6/4)'), (34, '2...16 (Default: 4/3)'), (35, '1...16/10/5 (Default: 6/4.5/3/1.8)'), (36, '2...12 (Default: 3)'), (37, '1...14 (Default: 8)'), (40, '0.5...16')], null=True, verbose_name='Несущая частота ШИМ, кГц'),
        ),
        migrations.AlterField(
            model_name='series',
            name='starting_torque',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '150% / 0.5 Гц'), (11, 'G type: 150% / 0.5 Гц (SVC)'), (12, 'G type: 150% / 0.5 Гц (SVC);\nP type: 100% / 0.5 Гц'), (13, '150% / 3 Гц (V/F), \n150% / 1 Гц (FVC)'), (14, '150% / 3 Гц (V/F, SVC для IM в тяжёлом режиме)\n100% / 2.5 Гц (V/F, SVC для PM в тяжёлом режиме)'), (15, '100% / 0.5 Гц (V/F); 150% / 0.5 Гц (SVC)'), (16, '150% / 3(1) Гц (V/F); 150% / 0.5 Гц (SVC)'), (17, 'G type: 150% / 0.5 Гц; \nP type: 100% / 0.5 Гц'), (18, 'Auto torque boost, manual torque boost 0.1%-30%; Vector torque boost 100-150; Start frequency 0.4Hz-20Hz'), (20, 'G type: 150% / 0.5 Гц (SVC), 180% / 0 Гц (VC);\nP type: 100% / 0.5 Гц'), (21, 'Auto torque boost, manual torque boost 0.1%-30%; Cut-off frequency of torque boost 0Hz to maximum output frequency')], null=True, verbose_name='Пусковой момент'),
        ),
    ]
