# Generated by Django 4.0.6 on 2022-09-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0158_remove_series_engine_cascade_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='railway_mounting',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Монтажный комплект на DIN-рейку'), (20, 'Да')], null=True, verbose_name='Монтаж на дин-рейку'),
        ),
        migrations.AlterField(
            model_name='series',
            name='inputs_outputs',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'DI: 4; AI: 1; TO: 0; RO: 1; AO: 1'), (20, 'DI: 4; AI: 2; TO: 0; RO: 1; AO: 1'), (30, 'DI: 5; AI: 1; TO: 1; RO: 1; AO: 1'), (40, 'DI: 6; AI: 2; TO: 0; RO: 1; AO: 1'), (41, 'DI: 5; AI: 2; TO: 1; RO: 1; AO: 1'), (50, 'DI: 6; AI: 2; TO: 1; RO: 2; AO: 2'), (51, 'DI: 6; AI: 2; TO: 2; RO: 1; AO: 2'), (60, 'DI: 7; AI: 2; TO: 3; RO: 1; AO: 1'), (61, 'DI: 7; AI: 2; TO: 2; RO: 2; AO: 1'), (62, 'DI: 8; AI: 2; TO: 2; RO: 1; AO: 1'), (70, 'DI: 7; AI: 3; TO: 2; RO: 1; AO: 2'), (80, 'DI: 10; AI: 3; TO: 0; RO: 3; AO: 2')], null=True, verbose_name='Входы/выходы'),
        ),
    ]
