# Generated by Django 4.0.6 on 2022-09-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0161_alter_series_maximum_output_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='inputs_outputs',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'DI: 4; AI: 1; TO: 0; RO: 1; AO: 1'), (20, 'DI: 4; AI: 2; TO: 0; RO: 1; AO: 1'), (30, 'DI: 5; AI: 1; TO: 1; RO: 1; AO: 1'), (40, 'DI: 6; AI: 2; TO: 0; RO: 1; AO: 1'), (41, 'DI: 5; AI: 2; TO: 1; RO: 1; AO: 1'), (50, 'DI: 6; AI: 2; TO: 1; RO: 2; AO: 2'), (51, 'DI: 6; AI: 2; TO: 2; RO: 1; AO: 2'), (60, 'DI: 7; AI: 2; TO: 3; RO: 1; AO: 1'), (61, 'DI: 7; AI: 2; TO: 2; RO: 2; AO: 1'), (62, 'DI: 8; AI: 2; TO: 2; RO: 1; AO: 1'), (70, 'DI: 7; AI: 3; TO: 2; RO: 1; AO: 2'), (80, 'DI: 10; AI: 3; TO: 0; RO: 3; AO: 2'), (81, 'DI: 8; AI: 3; TO: 2; RO: 2; AO: 2')], null=True, verbose_name='Входы/выходы'),
        ),
        migrations.AlterField(
            model_name='series',
            name='overload_capacity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Лёгкий режим: 120% 60с; \nНормальный режим: 120% 60с, 160% 3с'), (20, '150% 60с; 180% 3с'), (21, 'G type: 150% 60с, 180% 3с; \nP type: 120% 60с, 150% 3с'), (22, '150% 60с; 180% 2с; 200% 0.5c'), (23, 'G type: 150% 60с; 180% 3с'), (30, '110% длит.; 150% 60с; 180% 5с'), (31, 'Нормальный режим: 120% 60с, 150% 3с; \nТяжелый режим: 150% 60с, 200% 3с'), (32, 'G type: 110% длит.; 150% 60с, 200% 4с; \nP type: 105% длит.; 120% 60с, 150% 1с;'), (33, '150% 60с; 180% 10с; 200% 1c')], null=True, verbose_name='Перегрузочная способность'),
        ),
    ]
