# Generated by Django 4.0.6 on 2022-09-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0163_alter_series_carrier_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='choke_dc_link',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Опция от 75кВт'), (20, 'Опция 45...400кВт, встроен от 450кВт'), (30, 'Опция'), (40, 'Встроен на мощности 11, 15 кВт и от 200 кВт'), (50, 'Встроен на мощности от 45 кВт'), (60, 'Встроен на мощности от 37 кВт'), (70, 'Встроен')], null=True, verbose_name='Дроссель в звене постоянного тока'),
        ),
    ]
