# Generated by Django 4.0.6 on 2022-09-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0164_alter_series_choke_dc_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='motor_cable_length',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Без дросселя: до 50м; С дросселем: до 100м'), (11, 'Если длина кабелей двигателя превышает 50 м, рекомендуется использовать моторный дроссель.'), (20, 'Если длина кабелей двигателя превышает 100 м, рекомендуется использовать моторный дроссель.'), (30, 'Без дросселя: экран.кабель 35...100м в зависимости от номинала; неэкран. 50...150м. \nС дросселем: экран.кабель 50...150м; неэкран. 90...225м'), (40, 'Без дросселя: экран.кабель 50...150м в зависимости от номинала; неэкран. 75...225м. \nС дросселем: экран.кабель 75...225м; неэкран. 115...325м')], null=True, verbose_name='Максимальная длина кабеля двигателя'),
        ),
    ]
