# Generated by Django 4.0.6 on 2022-09-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0165_alter_series_motor_cable_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='removable_terminal_blocks',
        ),
    ]
