# Generated by Django 4.0.6 on 2022-09-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0166_remove_series_removable_terminal_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='use_relative_humidity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(20, 'Макс. 60%'), (40, 'Макс. 90%'), (50, 'Макс. 95%')], null=True, verbose_name='Относительная влажность при эксплуатации'),
        ),
    ]
