# Generated by Django 4.0.6 on 2022-09-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0167_alter_series_use_relative_humidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='removable_control_panel',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Для моделей от 22 кВт'), (20, 'Да')], null=True, verbose_name='Съёмная панель'),
        ),
        migrations.AlterField(
            model_name='series',
            name='control_panel_at_distance',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Да, при помощи кабеля-аксессуара'), (11, 'Да'), (20, 'Да, соединение обычным патч-кордом')], null=True, verbose_name='Выносная панель'),
        ),
        migrations.AlterField(
            model_name='series',
            name='inputs_outputs',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'DI: 4; AI: 1; TO: 0; RO: 1; AO: 1'), (20, 'DI: 4; AI: 2; TO: 0; RO: 1; AO: 1'), (30, 'DI: 5; AI: 1; TO: 1; RO: 1; AO: 1'), (40, 'DI: 6; AI: 2; TO: 0; RO: 1; AO: 1'), (41, 'DI: 5; AI: 2; TO: 1; RO: 1; AO: 1'), (50, 'DI: 5; AI: 2; TO: 1; RO: 2; AO: 2'), (60, 'DI: 6; AI: 2; TO: 1; RO: 2; AO: 2'), (61, 'DI: 6; AI: 2; TO: 2; RO: 1; AO: 2'), (70, 'DI: 7; AI: 2; TO: 3; RO: 1; AO: 1'), (71, 'DI: 7; AI: 2; TO: 2; RO: 2; AO: 1'), (72, 'DI: 8; AI: 2; TO: 2; RO: 1; AO: 1'), (80, 'DI: 7; AI: 3; TO: 2; RO: 1; AO: 2'), (81, 'DI: 8; AI: 2; TO: 2; RO: 2; AO: 2'), (90, 'DI: 10; AI: 3; TO: 0; RO: 3; AO: 2')], null=True, verbose_name='Входы/выходы'),
        ),
        migrations.AlterField(
            model_name='series',
            name='overload_capacity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Лёгкий режим: 120% 60с; \nНормальный режим: 120% 60с, 160% 3с'), (20, '150% 60с; 180% 3с'), (21, 'G type: 150% 60с, 180% 3с; \nP type: 120% 60с, 150% 3с'), (22, '150% 60с; 180% 2с; 200% 0.5c'), (23, 'G type: 150% 60с; 180% 3с'), (30, '110% длит.; 150% 60с; 180% 5с'), (31, 'Нормальный режим: 120% 60с, 150% 3с; \nТяжелый режим: 150% 60с, 200% 3с'), (32, 'G type: 110% длит.; 150% 60с, 200% 4с; \nP type: 105% длит.; 120% 60с, 150% 1с'), (33, '150% 60с; 180% 10с; 200% 1c'), (34, 'G type: 150% 60с; 180% 10с; 200% 1c; \nP type: 120% 60с')], null=True, verbose_name='Перегрузочная способность'),
        ),
        migrations.AlterField(
            model_name='series',
            name='starting_torque',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '150% / 0.5 Гц'), (11, 'G type: 150% / 0.5 Гц (SVC)'), (12, 'G type: 150% / 0.5 Гц (SVC);\nP type: 100% / 0.5 Гц'), (13, '150% / 3 Гц (V/F), \n150% / 1 Гц (FVC)'), (14, '150% / 3 Гц (V/F, SVC для IM в тяжёлом режиме)\n100% / 2.5 Гц (V/F, SVC для PM в тяжёлом режиме)'), (15, '100% / 0.5 Гц (V/F); 150% / 0.5 Гц (SVC)'), (16, '150% / 3(1) Гц (V/F); 150% / 0.5 Гц (SVC)'), (17, 'G type: 150% / 0.5 Гц; \nP type: 100% / 0.5 Гц'), (18, 'Auto torque boost, manual torque boost 0.1%-30%; Vector torque boost 100-150; Start frequency 0.4Hz-20Hz'), (19, '150% / 0.5 Гц (SVC)'), (20, 'G type: 150% / 0.5 Гц (SVC), 180% / 0 Гц (VC);\nP type: 100% / 0.5 Гц'), (21, 'Auto torque boost, manual torque boost 0.1%-30%; Cut-off frequency of torque boost 0Hz to maximum output frequency')], null=True, verbose_name='Пусковой момент'),
        ),
    ]
