# Generated by Django 4.0.6 on 2022-09-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0169_remove_series_control_panel_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='main_control_functions',
        ),
        migrations.AlterField(
            model_name='series',
            name='carrier_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(20, '2...12 (Default: 3)'), (21, '2...15'), (22, '2...15 (Default: 4)'), (23, '2...16 (Default: 4/3)'), (24, '1...16/10/5 (Default: 6/4.5/3/1.8)'), (25, '0.5...16'), (30, '2...15/10/9 (Default: 8/6/4)'), (31, '1...14 (Default: 8)'), (32, '1...15 (Default: 8/4/2)')], null=True, verbose_name='Несущая частота ШИМ, кГц'),
        ),
        migrations.AlterField(
            model_name='series',
            name='emc_filter',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, '1x230В: C3; 3x400В: контур ЭМС-фильтра'), (11, 'Контур ЭМС-фильтра'), (20, 'C3 (для эксплуатации в промышленной зоне)'), (30, 'C2 (для эксплуатации в жилой зоне)')], null=True, verbose_name='Встроенный EMC фильтр'),
        ),
    ]
