# Generated by Django 4.0.6 on 2022-09-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0171_alter_series_engine_protection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencydrive',
            name='current',
            field=models.FloatField(blank=True, null=True, verbose_name='Ток'),
        ),
    ]
