# Generated by Django 4.0.6 on 2022-10-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0173_series_cooling_fan_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='control_methods',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'V/F (скалярное управление)'), (20, 'V/F (скалярное управление), \nSVC (бездатчиковое векторное управление)'), (30, 'V/F (скалярное управление), \nSVC (бездатчиковое векторное управление), \nVC (векторное управление с замкнутым контуром)')], null=True, verbose_name='Методы управления'),
        ),
        migrations.AlterField(
            model_name='series',
            name='potentiometer',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Дополнительная плата потенциометра'), (20, 'Есть в панели управления')], null=True, verbose_name='Потенциометр'),
        ),
        migrations.AlterField(
            model_name='series',
            name='power_range',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...3.7кВт'), (11, '1x230В: 0.2...2.2кВт; 3x400В: 0.75...2.2кВт'), (20, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...5.5кВт'), (30, '1x230В: 0.2...2.2кВт; 3x400В: 0.4...7.5кВт'), (40, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...15кВт'), (50, '1x230В: 0.2...2.2кВт; 3x400В: 0.4...22кВт'), (51, '1x230В: 0.4...2.2кВт; 3x400В: 0.4...22кВт'), (60, '3x400В: 0.75...37кВт'), (70, '3x400В: 0.75...90кВт'), (80, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...110кВт'), (90, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...220кВт'), (91, '1x230В: 0.75...2.2кВт; 3x400В: 0.75...220кВт'), (100, '3x400В: 0.75...500кВт'), (101, '3x400В: 0.75...630кВт'), (102, '1x230В: 0.4...2.2кВт; 3x400В: 0.75...630кВт'), (103, '1x230В: 0.75...2.2кВт; 3x400В: 0.75...630кВт'), (104, '1x230В: 0.2...3.7кВт; 3x400В: 0.75...400кВт')], null=True, verbose_name='Диапазон мощностей'),
        ),
        migrations.AlterField(
            model_name='series',
            name='pre_configurations',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Группировка параметров по применениям'), (11, 'Макросы по применениям'), (20, 'Макросы, мастера настроек')], null=True, verbose_name='Предварительные конфигурации (Макросы)'),
        ),
    ]
