# Generated by Django 4.0.6 on 2022-10-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0174_alter_series_control_methods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='potentiometer',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Дополнительная плата потенциометра'), (20, 'Потенциометр в панели управления'), (30, 'Нажимное колёсико-энкодер')], null=True, verbose_name='Потенциометр'),
        ),
    ]
