# Generated by Django 4.0.6 on 2022-10-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0175_alter_series_potentiometer'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='package_set',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Плотный картон'), (30, 'Плотный картон, надувная пузырчатая пленка, сокращённый мануал')], null=True, verbose_name='Комплект поставки, упаковка'),
        ),
    ]
