# Generated by Django 4.0.6 on 2022-10-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0177_series_minimum_size_alter_series_carrier_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='case_quality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, 'Прочный корпус, качественная сборка; чёрный матовый, не вонючий пластик')], null=True, verbose_name='Качество корпуса'),
        ),
        migrations.AlterField(
            model_name='series',
            name='control_panel',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'LED 4x7'), (20, 'LED 5x7'), (30, 'LED двухстрочный'), (31, 'LED 5x7 (LCD опционально)'), (32, 'LED двухстрочный (LCD опционально)'), (40, 'LCD дисплей'), (41, 'LCD базовая (LCD интеллектуальная опционально)')], null=True, verbose_name='Панель управления'),
        ),
        migrations.AlterField(
            model_name='series',
            name='motor_cable_length',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Без дросселя: до 50м; С дросселем: до 100м'), (11, 'Если длина кабелей двигателя превышает 50 м, рекомендуется использовать моторный дроссель.'), (12, 'Без дросселя: до 50м; С дросселем: до 100м; EMC C3: до 30м'), (20, 'Если длина кабелей двигателя превышает 100 м, рекомендуется использовать моторный дроссель.'), (30, 'Без дросселя: экран.кабель 35...100м в зависимости от номинала; неэкран. 50...150м. \nС дросселем: экран.кабель 50...150м; неэкран. 90...225м'), (40, 'Без дросселя: экран.кабель 50...150м в зависимости от номинала; неэкран. 75...225м. \nС дросселем: экран.кабель 75...225м; неэкран. 115...325м')], null=True, verbose_name='Максимальная длина кабеля двигателя'),
        ),
    ]
