# Generated by Django 4.0.6 on 2022-10-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0179_series_installation_connection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='installation_connection',
        ),
    ]
