# Generated by Django 4.0.6 on 2022-11-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfd', '0180_remove_series_installation_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='control_panel',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'LED 4x7'), (20, 'LED 5x7'), (30, 'LED двухстрочный'), (31, 'LED 5x7 (LCD опционально)'), (32, 'LED двухстрочный (LCD опционально)'), (60, 'LCD дисплей'), (61, 'LCD базовая (LCD интеллектуальная опционально)')], null=True, verbose_name='Панель управления'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cooling_fan_control',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (20, 'Режим автоматического управления / работает всё время при включении питания'), (50, 'На выбор 5 режимов работы вентилятора'), (51, 'На выбор 4 режима работы вентилятора')], null=True, verbose_name='Управление вентилятором охлаждения'),
        ),
        migrations.AlterField(
            model_name='series',
            name='encoder_support',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Импульсный вход (плата расширения)'), (20, 'Импульсный вход'), (50, 'Плата расширения энкодера (ABZ, UVW, Rotary transformer)'), (51, 'Плата расширения энкодера')], null=True, verbose_name='Подключение энкодера'),
        ),
        migrations.AlterField(
            model_name='series',
            name='minimum_size',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, '212x95x154'), (40, '202x70x161'), (42, '142x72x159'), (50, '170x78x134'), (51, '142x72x143'), (41, '176x90x145'), (31, '186x125x170')], null=True, verbose_name='Минимальный габарит, ВхШхГ'),
        ),
        migrations.AlterField(
            model_name='series',
            name='package_set',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет'), (10, 'Простая упаковка: картон, две вставки из вспененного полиэтилена, пакет, силикагель'), (20, 'Плотный картон, вспененный полиэтилен, сокращённый мануал'), (21, 'Плотный картон, вспененный полиэтилен, полный мануал'), (22, 'Плотный картон, краткая инструкция по вводу в эксплуатацию'), (40, 'Плотный картон, надувная пузырчатая пленка, сокращённый мануал'), (41, 'Плотный картон, надувная пузырчатая пленка, полный мануал'), (42, 'Плотный картон, сокращённый мануал')], null=True, verbose_name='Комплект поставки, упаковка'),
        ),
    ]
