# Generated by Django 4.0.6 on 2022-09-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='country',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='EquipmentLine',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
