# Generated by Django 4.0.6 on 2022-09-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplier_country_delete_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Линейка оборудования',
                'verbose_name_plural': 'Линейки оборудования',
            },
        ),
    ]
