# Generated by Django 4.0.6 on 2022-09-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_equipmentline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('site', models.CharField(max_length=150, verbose_name='Сайт')),
                ('currency', models.CharField(choices=[('BYN', 'BYN'), ('RUB', 'RUB'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=200, verbose_name='Валюта')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ('name',),
            },
        ),
    ]
