# Generated by Django 4.0.6 on 2022-09-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('RUB', 'RUB'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='site',
            field=models.CharField(max_length=100, verbose_name='Сайт'),
        ),
    ]
