# Generated by Django 4.0.6 on 2022-09-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_alter_brand_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('id',), 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
