# Generated by Django 4.0.6 on 2022-09-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipsseries',
            options={'ordering': ('brand', 'name'), 'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
    ]
